### ISSUE TITLE
SAREF description is no longer valid (as SAREF was updated quite a while ago).

### ISSUE THREAD

**Issue by joakimeriksson** [BrickSchema/newsite#1]
The current description about SAREF is not valid anymore: 

_Smart Appliances REFerence Ontology (SAREF)  is an ontology capturing high level aspects of smart and connected appliances. While SAREF does not capture the the full spectrum of equipment and sensors that exist in buildings, SAREF models can be easily integrated into Brick._

Today it is Smart Applications REFerence Ontology - and it contains a core ontology and for example a SAREF4BLDG for building related modelling.

Today they describes it by the following:
_The Smart Applications REFerence (SAREF) suite of ontologies forms a shared model of consensus intended to enable semantic interoperability between solutions from different providers and among various activity sectors in the Internet of Things (IoT), thus contributing to the development of data spaces._

**Comment by gtfierro** [comment]
Thanks for letting us know! I've updated the text on the page
